# This is a basic workflow to help you get started with Actions

name: Build NodeJS Linux Amd64

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs apt-get
      - name: Install GCC, G++, and other needed tools...
        run: sudo apt-get install python3 python3-pip gcc make cmake git -y

      # Runs git clone
      - name: Clone the NodeJS Repo
        run: git clone --branch v17.5.0 --depth 1 https://github.com/NodeJS/Node NodeJS

      - name: Clone Javet
        run: git clone --branch 1.0.7 --depth 1 https://github.com/caoccao/Javet Javet

      - name: Configure the NodeJS build
        working-directory: ./NodeJS
        run: |
          python3 ../Javet/scripts/patch_node_build.py -p .
          ./configure --enable-static --without-intl
          python3 ../Javet/scripts/patch_node_build.py -p .

      - name: Build NodeJS
        working-directory: ./NodeJS
        run: |
          make -j4

      - name: Build Javet
        working-directory: ./Javet/cpp
        run: |
          export NODE_HOME=$(realpath ../..NodeJS)
          export JAVET_HOME=$(realpath ..)
          sh build-linux.sh -DNODE_DIR=${NODE_HOME}
