name: Transcrypt

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'

      - name: Transcrypt main.py
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          python3.9 -m pip install transcrypt
          python3.9 -m transcrypt test.py
          java -jar graaljs.jar __target__/test.js
